### ISSUE TITLE
Change of Working Directory

### ISSUE THREAD

**Issue by David-Kunz** [vhyrro/neorg#31] opened 2021-07-23 07:15 UTC
Hi,

When opening files, Neorg changes the working directory.

# Problems with that approach
Usually I work in a project and at some point in time I want to quickly add something to my TODO list, so I open my my `norg` file and add it. The moment I do this, I'm in a different working directory (which for example doesn't let me grep through my code base anymore).

# Steps to reproduce
1. Go into directory `~/foo`, open up Neovim
2. Open any `norg` file in the neorg directory: `:e ~/neorg/foo.norg`
3. See that it changed the working directory: `:pwd` (outputs `~/neorg`)

Thanks and best regards,
David

**Comment by vhyrro** [comment] 2021-07-23 07:36
Hi

After doing some testing, it seems that it's not an issue on our side (for the most part). Let me explain:
- The first thing you're encountering is "automatic detection of workspaces", which attempts to automatically set the Neorg workspace if it detects you've entered one. This can be disabled. This code snippet is taken from the wiki:
```lua
require('neorg').setup {
    load = {
        ["core.norg.dirman"] = {
            config = { -- Load a custom configuration

                workspaces = {
                    my_workspace = "~/neorg",
                    another_workspace = "~/dev/work/notes" -- Or wherever you want
                },
                       
                -- Automatically detect whenever we have entered a subdirectory of a workspace
                autodetect = true,

                -- Automatically change the directory to the root of the workspace every time 
                -- autochdir = true,
            }
        }
    }
}
```

I commented out the irrelevant options. You want to set the `autodetect` config variable to `false`, that way no automatic workspace changes will occur and you won't get locked in any directory anymore. This is only the first step though.
- The second thing you're encountering is simply Neovim behaviour. The cwd will change depending on which file you edit. I've tested this by opening a file in `/home/vhyrro` and then trying to edit a file in `~/test/file.txt`. Upon opening file.txt `:pwd` showed `/home/vhyrro/test`. That doesn't seem to be linked to Neorg in any way :)

**Comment by akinsho** [comment] 2021-07-23 08:37
FWIW I also hit this issue and I think there are a few things to note. Regarding neovim changing directory to the cwd of the file you are in, it doesn't actually do this by default there is an option to do it `autochdir` but that is `off` by default
> 'autochdir' 'acd'	boolean (default off)
			global
	When on, Vim will change the current working directory whenever you
	open a file, switch buffers, delete a buffer or open/close a window.
	It will change to the directory containing the file which was opened
	or selected.
	Note: When this option is on some plugins may not work.

I think the thing that is most inconvenient about the autodetect behaviour is that it doesn't switch the cwd back to what it was when you leave a norg file e.g. I open my dotfiles and am making some edit. I decide to open a `norg` file and the cwd is automatically set to the norg workspace I then go back to my init.lua and it doesn't switch my directory back.

Another issue is it's quite common for people to use rooter plugins like `vim-rooter` and `lsp-rooter` and so these conflict with this behaviour as well. I personally don't mind the norg workspace being the root when I'm in a norg file but I think that when I leave it should put things back the way they were initially.

**Comment by vhyrro** [comment] 2021-07-23 08:41
Yeah that's true. Currently you have to manually return back to where you were via `:Neorg return` (if you're on the unstable branch). I'll see if I can implement some logic later to try and make this process automatic (i.e. whenever a buffer gets switched to a file that isn't .norg it'll change the cwd back to what you'd expect).

**Comment by mrossinek** [comment] 2021-07-23 08:59
If I may chime in here, too: Although I personally disabled the `dirman` module of neorg, I also think that an effort to restore the previous cwd should be made.
I noticed that you use `:cd` but may I suggest using `:lcd` instead? This only changes the cwd for the _window_ and not the entire session. This will likely have less side-effects and is also the most fine-grained scope (see https://vimhelp.org/editing.txt.html#current-directory). `:lcd -` (https://vimhelp.org/editing.txt.html#%3Alcd-) might then be a good starting point to get back to where you were before.

**Comment by vhyrro** [comment] 2021-07-23 13:32
@David-Kunz I think I've managed to fix the issues :D

Be sure to use the `unstable` branch, as that is where I pushed the fixes (`unstable` is for features that aren't fully documented via wiki entries).

Directories should now get managed as expected. Workspaces will be set only if you're in a .norg buffer that is inside of a workspace. Once you leave it everything gets reset to the expected cwd. If you have any extra issues then please be sure to let me know.

**Comment by vhyrro** [comment] 2021-07-23 13:33
Oh and also I've switched to using `:lcd` now as per @mrossinek's request. Good call on that one.

**Comment by David-Kunz** [comment] 2021-07-23 14:29
Hi @vhyrro ,

Thanks so much for this fast reply and for the fix, I'm sure this will solve the problem.
Thank you all for this nice discussion!

🥇 

Best regards,
David

**Comment by vhyrro** [comment] 2021-07-25 19:33
If all is working as intended is it alright if we close down this thread until further issues arise? :)

**Closed** 2021-07-26 06:56 UTC
